UPLOAD_FOLDER = "data"
STATIC_FOLDER = "static"
RAW_FOLDER = "raw"
PROXY_FOLDER = "proxy"
SPLITTED_FOLDER = "splitted"
NGRAM_FOLDER = "ngramed"
PROCESSING_FOLDER = "processing"
DOWNLOAD_FOLDER = "download"
DONE_FOLDER = "done"
IMG_FOLDER = "img"
FORMAT_PLAIN = "txt"
FORMAT_TMX = "tmx"
RU_CODE = "ru"
ZH_CODE = "zh"
DE_CODE = "de"
EN_CODE = "en"
TYPE_FROM = "from"
TYPE_TO = "to"

EMPTY_LINES = {"items": {"ru":[], "zh":[]}}
EMPTY_SIMS = {"items": {"ru":[], "zh":[], "sim":[]}}
EMPTY_FILES = {"items": {"ru":[]}}